lint_node_18:
  image: node:18
  script:
    - yarn install
    - yarn run lint

lint_node_20:
  image: node:20
  script:
    - yarn install
    - yarn run lint

lint_node_latest:
  image: node:latest
  script:
    - yarn install
    - yarn run lint
